version: '3.2'
services:
    mariadb_statistics:
        image: 'mariadb'
        networks:
            - statistics_net
        environment:
            ALLOW_EMPTY_PASSWORD: 'no'
            MYSQL_DATABASE: 'statistics'
            MYSQL_USER: 'statuser'
            MYSQL_PASSWORD: 'statpass'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
            - /srv/themeeplers/statistics/mariadb:/var/lib/mysql/
        ports:
            - "3306:3306"
        deploy:
            mode: replicated
            replicas: 1
    #app_statistics:
        #image: 'qopbot/jre8-base:1.0'
        #networks:
            #- statistics_net
        #volumes:
            #- ./server.jar:/server.jar
        #ports:
            #- "8080:8080"
        #deploy:
            #mode: replicated
            #replicas: 1

networks:
    statistics_net:
        external: true

