version: '3.4'
services:
    mariadb_statistics:
        image: 'mariadb'
        networks:
            - statistics_net
        environment:
            ALLOW_EMPTY_PASSWORD: 'no'
            MYSQL_DATABASE: 'statistics'
            MYSQL_USER: 'statuser'
            MYSQL_PASSWORD: 'statpass'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
            - /srv/themeeplers/statistics/mariadb:/var/lib/mysql/
        deploy:
            mode: replicated
            replicas: 1
    app_statistics:
        image: 'qopbot/jre8-base:1.0'
        dns:
          - 8.8.8.8
          - 127.0.0.11
        networks:
          - statistics_net
        volumes:
            - /srv/themeeplers/statistics/server.jar:/server.jar
        secrets:
          - themeeplers-statistics-meetupKey
        ports:
          - "10000:8080"
        deploy:
            mode: replicated
            replicas: 1
secrets:
  themeeplers-statistics-meetupKey:
    external: true

networks:
    statistics_net:
        external: true

